// Generated by scripts/sync_musescore_commands.py; edit the QML source.
var version="2.11", selectionState={startStaff:0,endStaff:1,startTick:0,elements:[]};
    function processMessage(message, clientId) {
        console.log("Received message: " + message);
        try {
            var command = JSON.parse(message);
            var result = processCommand(command);
            api.websocketserver.send(clientId, JSON.stringify({
                status: "success",
                result: result
            }));
        } catch (e) {
            console.log("Error processing command: " + e.toString());
            api.websocketserver.send(clientId, JSON.stringify({
                status: "error",
                message: e.toString()
            }));
        }
    }
    function processCommand(command) {
        console.log("Processing command: " + command.action);
        
        switch(command.action) {
            // Core operations
            case "getScore":                return getScore(command.params);
            case "getScoreIdentity":        return getScoreIdentity();
            case "getCapabilities":         return getCapabilities();
            case "createScore":             return createScore(command.params);
            case "openScore":               return openScore(command.params);
            case "saveAs":                  return saveScoreAs(command.params);
            case "syncStateToSelection":    return syncStateToSelection();
            case "ping":                    return "pong";
            case "undo":                    return undo();
            case "goToBeginningOfScore":    return goToBeginningOfScore();
            case "processSequence":         return processSequence(command.params);
            case "save":                     return saveScore();

            // Navigation
            case "getCursorInfo":           return getCursorInfo(command.params);
            case "goToMeasure":             return goToMeasure(command.params);
            case "goToFinalMeasure":        return goToFinalMeasure(command.params);
            case "nextElement":             return nextElement(command.params);
            case "prevElement":             return prevElement(command.params);
            case "nextStaff":               return nextStaff(command.params);
            case "prevStaff":               return prevStaff(command.params);

            // Selection
            case "selectCurrentMeasure":    return selectCurrentMeasure(command.params);
            case "selectCustomRange":       return selectCustomRange(command.params);

            // Notes & Music
            case "addNote":                 return addNote(command.params);
            case "addChord":                return addChord(command.params);
            case "addTie":                  return addTie(command.params);
            case "addRest":                 return addRest(command.params);
            case "addTuplet":               return addTuplet(command.params);
            case "addTremolo": return addTremolo(command.params);
            case "addArpeggio": return addArpeggio(command.params);
            case "addFermata": return addFermata(command.params);
            case "addOrnament": return addOrnament(command.params);
            case "addPercussionNote": return addPercussionNote(command.params);
            case "getDrumset": return getDrumset(command.params);
            case "setNoteHead": return setNoteHead(command.params);
            case "setAccidental": return setAccidental(command.params);
            case "addGraceNotes": return addGraceNotes(command.params);
            case "addGraceSlur": return addGraceSlur(command.params);
            case "addGraceNote":            return addGraceNote(command.params);
            case "addLyrics":               return addLyrics(command.params);
            case "addDynamic":              return addDynamic(command.params);
            case "addArticulation":         return addArticulation(command.params);
            case "addSlur":                 return addSlur(command.params);
            case "addTechniqueText":        return addTechniqueText(command.params);

            // Measures
            case "appendMeasure":           return appendMeasure(command.params);
            case "insertMeasure":           return insertMeasure(command.params);
            case "deleteSelection":         return deleteSelection(command.params);

            // Staff & Instruments
            case "addInstrument":           return addInstrument(command.params);
            case "setStaffMute":            return setStaffMute(command.params);
            case "setStaffVisible":         return setStaffVisible(command.params);
            case "getMidiChannels":         return getMidiChannels(command.params);
            case "setMidiPatch":            return setMidiPatch(command.params);
            case "setPartInstrument":       return setPartInstrument(command.params);
            case "setInstrumentSound":      return setInstrumentSound(command.params);
            case "getPageLayout":           return getPageLayout();
            case "setPageLayout":           return setPageLayout(command.params);
            case "setLayoutBreak":          return setLayoutBreak(command.params);
            case "setKeySignature":         return setKeySignature(command.params);
            case "setTimeSignature":        return setTimeSignature(command.params);
            case "setTempo":                return setTempo(command.params);

            default:
                throw new Error("Unknown command: " + command.action);
        }
    }
    function validateParams(params, required) {
        if (!params) return { error: "Missing required parameters: " + required.join(", ") };
        var missing = [];
        for (var i = 0; i < required.length; i++) {
            if (params[required[i]] === undefined) {
                missing.push(required[i]);
            }
        }
        return missing.length > 0 ? { error: "Missing required parameters: " + missing.join(", ") } : { valid: true };
    }
    function executeWithUndo(operation) {
        if (!curScore) return { error: "No score open" };
        
        curScore.startCmd();
        try {
            var result = operation();
            curScore.endCmd();
            return result;
        } catch (e) {
            curScore.endCmd(true);
            return { error: e.toString() };
        }
    }
    function getNoteName(note) {
        const noteNames = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"];
        return noteNames[note % 12];
    }
    function getTpcName(tpc) {
        if (tpc === -1) return "Fbb";
        var tpcNames = [
            "Cbb", "Gbb", "Dbb", "Abb", "Ebb", "Bbb", "Fb",
            "Cb",  "Gb",  "Db",  "Ab",  "Eb",  "Bb",  "F",
            "C",   "G",   "D",   "A",   "E",   "B",   "F#",
            "C#",  "G#",  "D#",  "A#",  "E#",  "B#",  "F##",
            "C##", "G##", "D##", "A##", "E##", "B##", "F###"
        ];
        if (tpc >= 0 && tpc < tpcNames.length) {
            return tpcNames[tpc];
        }
        return "Unknown";
    }
    function getDurationName(duration) {
        const durationNames = ["LONG","BREVE","WHOLE","HALF","QUARTER","EIGHTH","16TH","32ND","64TH","128TH","256TH","512TH","1024TH","ZERO","MEASURE","INVALID"];
        return durationNames[duration] || "UNKNOWN";
    }
    function createCursor(params) {
        if (!curScore) throw new Error("No score open");
        
        if (!params || Object.keys(params).length === 0) {
            params = selectionState;
        }
        
        var cursor = curScore.newCursor();
        cursor.inputStateMode = Cursor.INPUT_STATE_SYNC_WITH_SCORE;
        
        // Set track
        if (params.startStaff !== undefined) cursor.staffIdx = params.startStaff;
        if (params.voice !== undefined) cursor.voice = params.voice;
        
        // Position cursor
        if (params.rewindMode !== undefined) {
            cursor.rewind(params.rewindMode);
        } else if (params.startTick !== undefined) {
            try {
                cursor.rewindToTick(params.startTick);
            } catch (e) {
                console.log("rewindToTick failed, using manual navigation");
                cursor.rewind(0);
                while (cursor.tick < params.startTick && cursor.next()) {}
            }
        } else if (params.measure !== undefined) {
            cursor.rewind(0);
            for (var i = 0; i < params.measure && cursor.nextMeasure(); i++) {}
        } else {
            cursor.rewind(0);
        }
        
        // Set duration
        if (params.duration) {
            cursor.setDuration(params.duration.numerator || 1, params.duration.denominator || 4);
        }
        
        return cursor;
    }
    function initCursorState() {
        if (!curScore) return "No score open";
        
        return executeWithUndo(function() {
            var cursor = curScore.newCursor();
            cursor.rewind(0);

            var startTick = cursor.tick;
            cursor.next();
            var endTick = cursor.tick;
            var element = cursor.element;

            selectionState = {
                startStaff: cursor.staffIdx,
                endStaff: cursor.staffIdx + 1,
                startTick: startTick,
                elements: element ? [processElement(element)] : []
            };
            
            curScore.selection.clear();
            curScore.selection.selectRange(startTick, endTick, 0, 0);
            
            return "Initialized at " + [startTick, endTick, 0, 0].join(',');
        });
    }
    function processElement(element) {
        if (!element) return null;
        if (element.name !== "Chord" && element.name !== "Rest") return null;

        var base = {
            name: element.name,
            durationTicks: element.actualDuration ? element.actualDuration.ticks : 0,
            isTie: element.tieForward ? true : false,
            isTuplet: element.tuplet ? true : false
        };

        if (element.lyrics && element.lyrics.length > 0) {
            base.lyrics = [];
            for (var l = 0; l < element.lyrics.length; l++) {
                var lyr = element.lyrics[l];
                if (lyr) {
                    base.lyrics.push({
                        text: lyr.text,
                        no: lyr.no,
                        syllabic: lyr.syllabic
                    });
                }
            }
        }

        if (element.name === "Chord") {
            base.notes = [];
            var notesObj = element.notes || {};
            var keys = Object.keys(notesObj);
            for (var k = 0; k < keys.length; k++) {
                var note = notesObj[keys[k]];
                base.notes.push({
                    pitchMidi: note.pitch,
                    tpc: note.tpc,
                    pitchName: getTpcName(note.tpc)
                });
            }
            base.graceNotes = [];
            for (var g = 0; g < element.graceNotes.length; g++) {
                var graceChord = element.graceNotes[g];
                var grace = { noteType: graceChord.noteType, notes: [] };
                for (var gn = 0; gn < graceChord.notes.length; gn++) {
                    grace.notes.push({
                        pitchMidi: graceChord.notes[gn].pitch,
                        tpc: graceChord.notes[gn].tpc,
                        pitchName: getTpcName(graceChord.notes[gn].tpc)
                    });
                }
                base.graceNotes.push(grace);
            }
        }
                
        return base;
    }
    function undo() {
        return executeWithUndo(function() {
            cmd("undo");
            return { success: true, message: "Undo successful" };
        });
    }
    function saveScore() {
        if (!curScore) return { error: "No score open" };
        try {
            cmd("file-save");
            return { success: true, message: "Current score saved" };
        } catch (e) {
            return { error: e.toString() };
        }
    }
    function createScore(params) {
        return { error: "createScore is not verified for MuseScore 4.7.4; open a score first" };
    }
    function openScore(params) {
        var validation = validateParams(params, ["path"]);
        if (!validation.valid) return validation;
        return { error: "openScore is not verified for MuseScore 4.7.4; use the extension backend with an explicit file" };
    }
    function saveScoreAs(params) {
        var validation = validateParams(params, ["path"]);
        if (!validation.valid) return validation;
        return { error: "saveAs is not verified for MuseScore 4.7.4; use save on the open score" };
    }
    function getCapabilities() {
        return {
            pluginVersion: version,
            commands: [
                "ping", "getCapabilities", "getScore", "getScoreIdentity", "save", "undo",
                "goToBeginningOfScore", "getCursorInfo", "goToMeasure",
                "goToFinalMeasure", "nextElement", "prevElement",
                "nextStaff", "prevStaff", "selectCurrentMeasure",
                "selectCustomRange", "processSequence", "addNote", "addChord", "addTie",
                "addRest", "addTuplet", "addGraceNote", "addGraceNotes", "addGraceSlur", "setAccidental", "setNoteHead", "addTremolo", "addArpeggio", "addFermata", "addOrnament", "addPercussionNote", "getDrumset", "addLyrics", "appendMeasure",
                "insertMeasure", "deleteSelection", "addInstrument",
                "getMidiChannels", "setPartInstrument",
                "getPageLayout", "setPageLayout", "setLayoutBreak",
                "setKeySignature", "setTimeSignature", "setTempo", "setStaffVisible",
                "addDynamic", "addTechniqueText", "addArticulation", "addSlur"
            ],
            reserved_commands: ["createScore", "openScore", "saveAs",
                                "setStaffMute", "setMidiPatch", "setInstrumentSound"]
        };
    }
    function getScoreIdentity() {
        if (!curScore) return { error: "No score open" };
        return {
            targetId: curScore.metaTag("scorebridgeTargetId") || "",
            scoreName: curScore.scoreName || "",
            title: curScore.metaTag("workTitle") || curScore.title || "",
            numMeasures: curScore.nmeasures,
            numStaves: curScore.nstaves
        };
    }
    function goToBeginningOfScore() {
        var response = initCursorState();
        return { 
            success: true, 
            message: response, 
            currentSelection: selectionState,
            currentScore: getScoreSummary()
        };
    }
    function processSequence(params) {
        if (!curScore) return { error: "No score open" };
        if (!params || !Array.isArray(params.sequence)) return { error: "Sequence must be an array" };

        var validCommands = [
            "getCapabilities", "getScore",
            "addNote", "addChord", "addTie", "addRest", "addTuplet", "addGraceNote", "addGraceNotes", "addGraceSlur", "setAccidental", "setNoteHead", "addTremolo", "addArpeggio", "addFermata", "addOrnament", "addPercussionNote", "getDrumset", "appendMeasure", "deleteSelection",
            "getCursorInfo", "goToMeasure", "nextElement", "prevElement", "nextStaff", "prevStaff", "save",
            "selectCurrentMeasure", "processSequence", "insertMeasure", "goToFinalMeasure",
            "getMidiChannels", "setPartInstrument",
            "getPageLayout", "setPageLayout", "setLayoutBreak",
            "goToBeginningOfScore", "setKeySignature", "setTimeSignature", "addLyrics", "addInstrument",
            "setStaffVisible", "setTempo", "selectCustomRange", "addDynamic", "addTechniqueText", "addArticulation", "addSlur"
        ];

        var completed = [];
        var i = 0;
        try {
            for (i = 0; i < params.sequence.length; i++) {
                var command = params.sequence[i];
                if (!command || !validCommands.includes(command.action)) {
                    throw new Error("Invalid command at index " + i);
                }
                var result = processCommand(command);
                if (result && (result.error || result.success === false || result.valid === false)) {
                    return { error: result.error || "Command failed", failedIndex: i,
                             completedIndices: completed, result: result };
                }
                completed.push(i);
            }
            return { success: true, completedIndices: completed, message: "Sequence processed", currentSelection: selectionState };
        } catch (e) {
            return { error: e.toString(), failedIndex: i, completedIndices: completed };
        }
    }
    function syncStateToSelection() {
        if (!curScore) return { error: "No score open" };

        try {
            var selection = curScore.selection;
            var startSegment = selection.startSegment;
            var endSegment = selection.endSegment;

            if (startSegment && endSegment) {
                var cursor = createCursor({
                    startTick: startSegment.tick,
                    startStaff: selection.startStaff    
                });

                var elementsMap = {};
                for (var st = selection.startStaff; st < selection.endStaff; st++) {
                    elementsMap[`staff${st}`] = [];
                }

                var currentSegment = startSegment;
                while (currentSegment && currentSegment.tick < endSegment.tick) {
                    for (var s = selection.startStaff; s < selection.endStaff; s++) {
                        for (var v = 0; v < 4; v++) {
                            var track = s * 4 + v;
                            var el = currentSegment.elementAt(track);
                            if (el) {
                                var processed = processElement(el);
                                if (processed) {
                                    processed.voice = v;
                                    processed.startTick = currentSegment.tick;
                                    elementsMap[`staff${s}`].push(processed);
                                }
                            }
                        }
                    }
                    currentSegment = currentSegment.next;
                }

                selectionState = {
                    startStaff: selection.startStaff,
                    endStaff: selection.endStaff,
                    startTick: startSegment.tick,
                    elements: elementsMap,
                    totalDuration: endSegment.tick - startSegment.tick
                };
            } else {
                var c = createCursor();
                if (c && c.element) {
                    var elElement = processElement(c.element);
                    elElement.startTick = c.tick;
                    var sStart = selection.startStaff || 0;
                    var singleMap = {};
                    singleMap[`staff${sStart}`] = [elElement];
                    
                    selectionState = {
                        startStaff: sStart,
                        endStaff: sStart + 1,
                        startTick: c.tick,
                        elements: singleMap,
                        totalDuration: elElement.durationTicks
                    };
                } else {
                    return { error: "No valid selection or cursor elements found" };
                }
            }

            return { success: true, currentSelection: selectionState };
        } catch (e) {
            return { success: false, error: e.toString() };
        }
    }
    function getCursorInfo(params) {
        if (!curScore) return { error: "No score open" };
        
        syncStateToSelection();
        return { 
            success: true, 
            currentSelection: selectionState, 
            currentScore: params && params.verbose !== "false" ? getScoreSummary() : null
        };
    }
    function goToMeasure(params) {
        var validation = validateParams(params, ["measure"]);
        if (!validation.valid) return validation;

        return executeWithUndo(function() {
            var score = getScoreSummary();
            if (params.measure < 1 || params.measure > score.measures.length) {
                return { error: "Invalid measure number" };
            }
            var measureIdx = params.measure - 1;
            var measure = score.measures[measureIdx];
            var startTick = measure.startTick;
            
            var endTick = (measureIdx + 1 < score.measures.length) ? score.measures[measureIdx + 1].startTick : curScore.lastSegment.tick;
            
            curScore.selection.clear();
            curScore.selection.selectRange(startTick, endTick, 0, curScore.nstaves);
            
            var res = syncStateToSelection();
            if (res.error) return res;
            
            return { success: true, currentSelection: selectionState };
        });
    }
    function nextElement(params) {
        return executeWithUndo(function() {
            syncStateToSelection();
            
            var cursor = createCursor({ 
                startTick: selectionState.startTick, 
                startStaff: selectionState.startStaff 
            });

            var numElements = params && params.numElements || 1;
            var success = true;
            for (var i = 0; i < numElements && success; i++) {
                success = cursor.next();
            }
            
            if (success) {
                var element = processElement(cursor.element);
                var startTick = cursor.tick;
                var staffIdx = cursor.staffIdx;
                
                // Check if we need to append a measure
                if (startTick + element.durationTicks >= curScore.lastSegment.tick) {
                    cmd("append-measure");
                }

                curScore.selection.clear();
                curScore.selection.selectRange(startTick, startTick + element.durationTicks, staffIdx, staffIdx + 1);

                selectionState = {
                    startStaff: staffIdx,
                    endStaff: staffIdx + 1,
                    startTick: startTick,
                    elements: [element],
                    totalDuration: element.durationTicks
                };
                
                return { success: true, currentSelection: selectionState };
            } else {
                return { success: false, message: "End of score reached" };
            }
        });
    }
    function prevElement(params) {
        return executeWithUndo(function() {
            syncStateToSelection();
            
            var cursor = createCursor({ 
                startTick: selectionState.startTick, 
                startStaff: selectionState.startStaff 
            });

            var endTick = cursor.tick;
            var numElements = params && params.numElements || 1;
            var success = true;
            
            for (var i = 0; i < numElements && success; i++) {
                success = cursor.prev();
            }

            if (success) {
                var element = processElement(cursor.element);
                var startTick = cursor.tick;
                var staffIdx = cursor.staffIdx;
                
                curScore.selection.clear();
                curScore.selection.selectRange(startTick, endTick, staffIdx, staffIdx + 1);

                selectionState = {
                    startStaff: staffIdx,
                    endStaff: staffIdx + 1,
                    startTick: startTick,
                    elements: [element],
                    totalDuration: endTick - startTick
                };
                
                return { success: true, currentSelection: selectionState };
            } else {
                return { success: false, message: "Beginning of score reached" };
            }
        });
    }
    function nextStaff(params) {
        return executeWithUndo(function() {
            syncStateToSelection();

            if (selectionState.endStaff >= curScore.nstaves) {
                return { success: false, message: "Already at last staff" };
            }

            var newStaff = selectionState.endStaff;
            var cursor = createCursor({ 
                startTick: selectionState.startTick, 
                startStaff: newStaff 
            });

            var element = processElement(cursor.element);
            
            curScore.selection.clear();
            curScore.selection.selectRange(
                selectionState.startTick, 
                selectionState.startTick + element.durationTicks, 
                newStaff, 
                newStaff + 1
            );

            selectionState = {
                startStaff: newStaff,
                endStaff: newStaff + 1,
                startTick: selectionState.startTick,
                elements: [element],
                totalDuration: element.durationTicks
            };

            return { success: true, currentSelection: selectionState };
        });
    }
    function prevStaff(params) {
        return executeWithUndo(function() {
            syncStateToSelection();

            if (selectionState.startStaff <= 0) {
                return { success: false, message: "Already at first staff" };
            }

            var newStaff = selectionState.startStaff - 1;
            var cursor = createCursor({ 
                startTick: selectionState.startTick, 
                startStaff: newStaff 
            });

            var element = processElement(cursor.element);
            
            curScore.selection.clear();
            curScore.selection.selectRange(
                selectionState.startTick, 
                selectionState.startTick + element.durationTicks, 
                newStaff, 
                newStaff + 1
            );

            selectionState = {
                startStaff: newStaff,
                endStaff: newStaff + 1,
                startTick: selectionState.startTick,
                elements: [element],
                totalDuration: element.durationTicks
            };

            return { success: true, currentSelection: selectionState };
        });
    }
    function goToFinalMeasure(params) {
        return executeWithUndo(function() {
            var cursor = createCursor({ startTick: 0 });
            var count = 0;
            var startTick = 0;

            while (cursor.nextMeasure()) {
                startTick = cursor.tick;
                count++;
            }

            if (count === 0) {
                return { success: false, message: "Already at the last measure" };
            }

            cursor.rewindToTick(startTick);
            cursor.next();
            var endTick = cursor.tick;
            var staffIdx = cursor.staffIdx;
            
            curScore.selection.clear();
            curScore.selection.selectRange(startTick, endTick, staffIdx, staffIdx + 1);
            
            selectionState = {
                startStaff: staffIdx,
                endStaff: staffIdx + 1,
                startTick: startTick,
                elements: [processElement(cursor.element)],
                totalDuration: endTick - startTick
            };

            return { success: true, currentSelection: selectionState };
        });
    }
    function selectCurrentMeasure() {
        return executeWithUndo(function() {
            var cursor = createCursor({ 
                startTick: selectionState.startTick || 0, 
                startStaff: selectionState.startStaff || 0 
            });

            var currTick = cursor.tick;
            var scoreSummary = getScoreSummary();

            var measureIdx = scoreSummary.measures.filter(function(m) { 
                return m.startTick <= currTick; 
            }).length - 1;
            
            if (measureIdx < 0) return { error: "Invalid cursor position" };
            
            var measure = scoreSummary.measures[measureIdx];
            var startTick = measure.startTick;
            var endTick = (measureIdx + 1 < scoreSummary.measures.length) ? scoreSummary.measures[measureIdx + 1].startTick : curScore.lastSegment.tick;

            curScore.selection.clear();
            curScore.selection.selectRange(startTick, endTick, 0, curScore.nstaves);

            var res = syncStateToSelection();
            if (res.error) return res;
            
            return { success: true, message: `Selected measure ${measureIdx + 1}`, currentSelection: selectionState };
        });
    }
    function selectCustomRange(params) {
        var validation = validateParams(params, ["startTick", "endTick", "startStaff", "endStaff"]);
        if (!validation.valid) return validation;

        return executeWithUndo(function() {
            var startTick = params.startTick;
            var endTick = params.endTick;
            var startStaff = params.startStaff;
            var endStaff = params.endStaff;

            // Visual GUI snap
            curScore.selection.clear();
            curScore.selection.selectRange(startTick, endTick, startStaff, endStaff);

            var elementsMap = {};
            for (var st = startStaff; st < endStaff; st++) {
                elementsMap[`staff${st}`] = [];
            }

            var c = createCursor({ startTick: 0, startStaff: startStaff });
            c.rewind(0);
            var currentSegment = c.segment;

            while (currentSegment && currentSegment.tick < startTick) {
                currentSegment = currentSegment.next;
            }

            while (currentSegment && currentSegment.tick < endTick) {
                for (var s = startStaff; s < endStaff; s++) {
                    for (var v = 0; v < 4; v++) {
                        var track = s * 4 + v;
                        var el = currentSegment.elementAt(track);
                        if (el) {
                            var processed = processElement(el);
                            if (processed) {
                                processed.voice = v;
                                processed.startTick = currentSegment.tick;
                                elementsMap[`staff${s}`].push(processed);
                            }
                        }
                    }
                }
                currentSegment = currentSegment.next;
            }

            selectionState = {
                startStaff: startStaff,
                endStaff: endStaff,
                startTick: startTick,
                elements: elementsMap,
                totalDuration: endTick - startTick
            };

            return { success: true, message: "Custom range mapped", currentSelection: selectionState };
        });
    }
    function addNote(params) {
        var validation = validateParams(params, ["pitch", "duration"]);
        if (!validation.valid) return validation;

        if (!params.duration.numerator || !params.duration.denominator) {
            return { error: "Duration must be specified as { numerator: int, denominator: int }" };
        }

        return executeWithUndo(function() {
            syncStateToSelection();
            
            var cursorParams = {};
            if (params.staff !== undefined) cursorParams.startStaff = params.staff;
            if (params.startTick !== undefined) cursorParams.startTick = params.startTick;
            if (params.voice !== undefined) cursorParams.voice = params.voice;
            var cursor = createCursor(cursorParams);
            cursor.setDuration(params.duration.numerator, params.duration.denominator);
            
            // Melody is the default. Pass addToChord: true to stack a pitch on the current chord.
            cursor.addNote(params.pitch, params.addToChord === true);
            cursor.rewindToTick(selectionState.startTick);

            if (params.advanceCursorAfterAction) {
                cursor.next();
            }

            var element = processElement(cursor.element);
            var startTick = cursor.tick;
            var staffIdx = cursor.staffIdx;
            var durationTicks = element && element.durationTicks ? element.durationTicks : 0;

            curScore.selection.clear();
            if (durationTicks > 0) {
                curScore.selection.selectRange(startTick, startTick + durationTicks, staffIdx, staffIdx + 1);
            }

            var syncRes = syncStateToSelection();
            if (syncRes && syncRes.error) {
                var staffMap = {};
                staffMap["staff" + staffIdx] = element ? [element] : [];
                selectionState = {
                    startStaff: staffIdx,
                    endStaff: staffIdx + 1,
                    startTick: startTick,
                    elements: staffMap,
                    totalDuration: durationTicks
                };
            }

            return { 
                success: true, 
                message: "Note added with pitch " + params.pitch,
                currentSelection: selectionState
            };
        });
    }
    function addChord(params) {
        if (!curScore) return { error: "No score open" };
        if (!params || !Array.isArray(params.pitches) || params.pitches.length === 0)
            return { error: "pitches must be a nonempty array of MIDI pitches" };
        if (!params.duration || !Number.isInteger(params.duration.numerator) ||
            !Number.isInteger(params.duration.denominator) || params.duration.numerator <= 0 ||
            params.duration.denominator <= 0)
            return { error: "duration must contain positive integer numerator and denominator" };
        var staff = params.staff === undefined ? selectionState.startStaff : params.staff;
        var voice = params.voice === undefined ? 0 : params.voice;
        var startTick = params.startTick === undefined ? selectionState.startTick : params.startTick;
        if (!Number.isInteger(staff) || staff < 0 || staff >= curScore.nstaves)
            return { error: "staff must be a valid zero-based staff index" };
        if (!Number.isInteger(voice) || voice < 0 || voice > 3)
            return { error: "voice must be an integer from 0 to 3" };
        if (!Number.isInteger(startTick) || startTick < 0)
            return { error: "startTick must be a nonnegative integer" };
        var seen = {};
        for (var i = 0; i < params.pitches.length; i++) {
            var pitch = params.pitches[i];
            if (!Number.isInteger(pitch) || pitch < 0 || pitch > 127)
                return { error: "Every pitch must be an integer from 0 to 127" };
            if (seen[pitch]) return { error: "Duplicate pitches are not allowed in a chord" };
            seen[pitch] = true;
        }
        if (params.tpcs !== undefined) {
            if (!Array.isArray(params.tpcs) || params.tpcs.length !== params.pitches.length)
                return { error: "tpcs must be an array matching pitches" };
            if (curScore.style.value("concertPitch"))
                return { error: "Written TPC input requires the score's concert pitch display to be off" };
            for (var j = 0; j < params.tpcs.length; j++) {
                if (!Number.isInteger(params.tpcs[j]) || params.tpcs[j] < -1 || params.tpcs[j] > 35)
                    return { error: "Every TPC must be an integer from -1 to 35" };
            }
        }
        return executeWithUndo(function() {
            // Locate on the staff before switching voice. An empty secondary voice has
            // no chord/rest segment for rewindToTick() to find until MuseScore expands it.
            var cursor = createCursor({startStaff: staff, startTick: startTick});
            if (cursor.tick !== startTick)
                throw new Error("No score position exists at startTick " + startTick);
            cursor.voice = voice;
            cursor.setDuration(params.duration.numerator, params.duration.denominator);
            for (var p = 0; p < params.pitches.length; p++) {
                if (p > 0) cursor.rewindToTick(startTick);
                cursor.addNote(params.pitches[p], p > 0);
            }
            cursor.rewindToTick(startTick);
            var chord = cursor.element;
            if (!chord || chord.type !== Element.CHORD)
                throw new Error("MuseScore did not create a chord at the requested position");
            var written = [];
            for (var q = 0; q < params.pitches.length; q++) {
                var matched = null;
                for (var n = 0; n < chord.notes.length; n++) {
                    if (chord.notes[n].pitch === params.pitches[q]) { matched = chord.notes[n]; break; }
                }
                if (!matched) throw new Error("MuseScore did not retain pitch " + params.pitches[q]);
                if (params.tpcs !== undefined) {
                    matched.tpc = params.tpcs[q];
                    if (matched.tpc !== params.tpcs[q])
                        throw new Error("MuseScore did not retain TPC " + params.tpcs[q]);
                }
                written.push({pitch: matched.pitch, tpc: matched.tpc});
            }
            var durationTicks = chord.actualDuration ? chord.actualDuration.ticks : 0;
            if (durationTicks <= 0) throw new Error("MuseScore created a zero-duration chord");
            curScore.selection.clear();
            curScore.selection.selectRange(startTick, startTick + durationTicks, staff, staff + 1);
            selectionState = {startStaff: staff, endStaff: staff + 1, startTick: startTick,
                              elements: [processElement(chord)], totalDuration: durationTicks};
            return {success: true, changed: true, staff: staff, voice: voice,
                    startTick: startTick, durationTicks: durationTicks, notes: written,
                    currentSelection: selectionState};
        });
    }
    function addTie(params) {
        if (!curScore) return { error: "No score open" };
        if (!params || !Number.isInteger(params.staff) || params.staff < 0 || params.staff >= curScore.nstaves)
            return { error: "staff must be a valid zero-based staff index" };
        if (!Number.isInteger(params.voice) || params.voice < 0 || params.voice > 3)
            return { error: "voice must be an integer from 0 to 3" };
        if (!Number.isInteger(params.startTick) || params.startTick < 0)
            return { error: "startTick must be a nonnegative integer" };
        if (!Number.isInteger(params.pitch) || params.pitch < 0 || params.pitch > 127)
            return { error: "pitch must be an integer from 0 to 127" };
        return executeWithUndo(function() {
            var cursor = createCursor({startStaff: params.staff, voice: params.voice, startTick: params.startTick});
            if (cursor.tick !== params.startTick || !cursor.element || cursor.element.type !== Element.CHORD)
                throw new Error("No source chord exists at the requested position");
            var source = null;
            for (var i = 0; i < cursor.element.notes.length; i++) {
                if (cursor.element.notes[i].pitch === params.pitch) { source = cursor.element.notes[i]; break; }
            }
            if (!source) throw new Error("Source chord does not contain pitch " + params.pitch);
            if (source.tieForward)
                return {success: true, changed: false, staff: params.staff, voice: params.voice,
                        startTick: params.startTick, pitch: params.pitch};
            if (!cursor.next() || !cursor.element || cursor.element.type !== Element.CHORD)
                throw new Error("The next event in this voice is not a chord");
            var targetTick = cursor.tick;
            var targetFound = false;
            for (var j = 0; j < cursor.element.notes.length; j++) {
                if (cursor.element.notes[j].pitch === params.pitch) { targetFound = true; break; }
            }
            if (!targetFound) throw new Error("The next chord does not contain matching pitch " + params.pitch);
            curScore.selection.clear();
            curScore.selection.select(source, false);
            cmd("tie");
            var verify = createCursor({startStaff: params.staff, voice: params.voice, startTick: params.startTick});
            var tied = null;
            for (var k = 0; verify.element && k < verify.element.notes.length; k++) {
                if (verify.element.notes[k].pitch === params.pitch) { tied = verify.element.notes[k]; break; }
            }
            if (!tied || !tied.tieForward || !tied.tieForward.endNote ||
                tied.tieForward.endNote.pitch !== params.pitch)
                throw new Error("MuseScore did not create the requested tie");
            return {success: true, changed: true, staff: params.staff, voice: params.voice,
                    startTick: params.startTick, endTick: targetTick, pitch: params.pitch};
        });
    }
    function addRest(params) {
        if (!curScore) return { error: "No score open" };
        params = params || {};
        var staff = params.staff !== undefined ? params.staff : selectionState.startStaff;
        var voice = params.voice !== undefined ? params.voice : 0;
        var startTick = params.startTick !== undefined ? params.startTick : selectionState.startTick;
        if (!Number.isInteger(staff) || staff < 0 || staff >= curScore.nstaves)
            return { error: "staff must be a valid zero-based staff index" };
        if (!Number.isInteger(voice) || voice < 0 || voice > 3)
            return { error: "voice must be an integer from 0 to 3" };
        if (!Number.isInteger(startTick) || startTick < 0)
            return { error: "startTick must be a nonnegative integer" };
        if (!params.duration || !Number.isInteger(params.duration.numerator) ||
            !Number.isInteger(params.duration.denominator) || params.duration.numerator <= 0 ||
            params.duration.denominator <= 0)
            return { error: "duration must contain positive integer numerator and denominator" };
        return executeWithUndo(function() {
            // Find the rhythmic position before selecting the voice. This also
            // lets MuseScore expand an empty secondary voice when addRest runs.
            var cursor = createCursor({startStaff: staff, startTick: startTick});
            if (cursor.tick !== startTick)
                throw new Error("No score position exists at startTick " + startTick);
            cursor.voice = voice;
            cursor.setDuration(params.duration.numerator, params.duration.denominator);
            cursor.addRest();
            cursor.rewindToTick(startTick);
            if (!cursor.element || cursor.element.type !== Element.REST)
                throw new Error("MuseScore did not create a rest at the requested position");
            var durationTicks = cursor.element.actualDuration ? cursor.element.actualDuration.ticks : 0;
            if (durationTicks <= 0) throw new Error("MuseScore created a zero-duration rest");
            curScore.selection.clear();
            curScore.selection.selectRange(startTick, startTick + durationTicks, staff, staff + 1);
            selectionState = {
                startStaff: staff,
                endStaff: staff + 1,
                startTick: startTick,
                elements: [processElement(cursor.element)],
                totalDuration: durationTicks
            };
            return {success: true, changed: true, staff: staff, voice: voice,
                    startTick: startTick, durationTicks: durationTicks,
                    currentSelection: selectionState};
        });
    }
    function addTuplet(params) {
        if (!curScore) return { error: "No score open" };
        params = params || {};
        if (!Number.isInteger(params.staff) || params.staff < 0 || params.staff >= curScore.nstaves)
            return { error: "staff must be a valid zero-based staff index" };
        if (!Number.isInteger(params.voice) || params.voice < 0 || params.voice > 3)
            return { error: "voice must be an integer from 0 to 3" };
        if (!Number.isInteger(params.startTick) || params.startTick < 0)
            return { error: "startTick must be a nonnegative integer" };
        if (!params.ratio || !Number.isInteger(params.ratio.numerator) ||
            !Number.isInteger(params.ratio.denominator) || params.ratio.numerator <= 0 ||
            params.ratio.denominator <= 0)
            return { error: "ratio must contain positive integer numerator and denominator" };
        if (!params.duration || !Number.isInteger(params.duration.numerator) ||
            !Number.isInteger(params.duration.denominator) || params.duration.numerator <= 0 ||
            params.duration.denominator <= 0)
            return { error: "duration must contain positive integer numerator and denominator" };
        return executeWithUndo(function() {
            var cursor = createCursor({startStaff: params.staff, startTick: params.startTick});
            if (cursor.tick !== params.startTick)
                throw new Error("No score position exists at startTick " + params.startTick);
            cursor.voice = params.voice;
            cursor.setDuration(params.duration.numerator, params.duration.denominator);
            var ratio = fraction(params.ratio.numerator, params.ratio.denominator);
            var duration = fraction(params.duration.numerator, params.duration.denominator);
            cursor.addTuplet(ratio, duration);
            cursor.rewindToTick(params.startTick);
            var element = cursor.element;
            if (!element || !element.tuplet)
                throw new Error("MuseScore did not create a tuplet at the requested position");
            if (element.tuplet.actualNotes !== params.ratio.numerator ||
                element.tuplet.normalNotes !== params.ratio.denominator)
                throw new Error("MuseScore created a different tuplet ratio");
            var tupletTicks = element.tuplet.actualDuration ? element.tuplet.actualDuration.ticks : 0;
            if (tupletTicks <= 0) throw new Error("MuseScore created a zero-duration tuplet");
            curScore.selection.clear();
            curScore.selection.selectRange(params.startTick, params.startTick + tupletTicks,
                                           params.staff, params.staff + 1);
            selectionState = {startStaff: params.staff, endStaff: params.staff + 1,
                              startTick: params.startTick, elements: [processElement(element)],
                              totalDuration: tupletTicks};
            return {success: true, changed: true, staff: params.staff, voice: params.voice,
                    startTick: params.startTick, durationTicks: tupletTicks,
                    ratio: {numerator: element.tuplet.actualNotes,
                            denominator: element.tuplet.normalNotes},
                    currentSelection: selectionState};
        });
    }
    function addGraceNote(params) {
        if (!curScore) return { error: "No score open" };
        if (!params || typeof params.type !== "string")
            return { error: "type must identify a supported grace note" };
        var actions = {
            acciaccatura: "acciaccatura",
            appoggiatura: "appoggiatura",
            grace4: "grace4",
            grace16: "grace16",
            grace32: "grace32",
            grace8after: "grace8after",
            grace16after: "grace16after",
            grace32after: "grace32after"
        };
        if (!Object.prototype.hasOwnProperty.call(actions, params.type))
            return { error: "Unsupported grace note type: " + params.type };
        if (!Number.isInteger(params.staff) || params.staff < 0 || params.staff >= curScore.nstaves)
            return { error: "staff must be a valid zero-based staff index" };
        var voice = params.voice === undefined ? 0 : params.voice;
        if (!Number.isInteger(voice) || voice < 0 || voice > 3)
            return { error: "voice must be an integer from 0 to 3" };
        if (!Number.isInteger(params.startTick) || params.startTick < 0)
            return { error: "startTick must be a nonnegative integer" };
        if (!Number.isInteger(params.pitch) || params.pitch < 0 || params.pitch > 127)
            return { error: "pitch must be an integer from 0 to 127" };
        if (params.anchorPitch !== undefined && (!Number.isInteger(params.anchorPitch) ||
            params.anchorPitch < 0 || params.anchorPitch > 127))
            return { error: "anchorPitch must be an integer from 0 to 127" };
        if (params.tpc !== undefined) {
            if (!Number.isInteger(params.tpc) || params.tpc < -1 || params.tpc > 35)
                return { error: "tpc must be an integer from -1 to 35" };
            if (curScore.style.value("concertPitch"))
                return { error: "Written TPC input requires the score's concert pitch display to be off" };
        }
        var expectedTypes = {
            acciaccatura: NoteType.ACCIACCATURA,
            appoggiatura: NoteType.APPOGGIATURA,
            grace4: NoteType.GRACE4,
            grace16: NoteType.GRACE16,
            grace32: NoteType.GRACE32,
            grace8after: NoteType.GRACE8_AFTER,
            grace16after: NoteType.GRACE16_AFTER,
            grace32after: NoteType.GRACE32_AFTER
        };
        return executeWithUndo(function() {
            var cursor = createCursor({startStaff: params.staff, voice: voice, startTick: params.startTick});
            if (cursor.tick !== params.startTick || !cursor.element || cursor.element.type !== Element.CHORD)
                throw new Error("No main chord exists at the requested position");
            var mainChord = cursor.element;
            var anchor = null;
            for (var n = 0; n < mainChord.notes.length; n++) {
                if (params.anchorPitch === undefined || mainChord.notes[n].pitch === params.anchorPitch) {
                    anchor = mainChord.notes[n];
                    break;
                }
            }
            if (!anchor) throw new Error("The main chord does not contain anchorPitch " + params.anchorPitch);
            var existing = [];
            for (var g = 0; g < mainChord.graceNotes.length; g++) existing.push(mainChord.graceNotes[g]);
            curScore.selection.clear();
            curScore.selection.select(anchor, false);
            cmd(actions[params.type]);

            var verify = createCursor({startStaff: params.staff, voice: voice, startTick: params.startTick});
            if (verify.tick !== params.startTick || !verify.element || verify.element.type !== Element.CHORD)
                throw new Error("Main chord disappeared after adding the grace note");
            var graceList = verify.element.graceNotes;
            if (graceList.length !== existing.length + 1)
                throw new Error("MuseScore did not create exactly one grace note");
            var created = null;
            for (var i = 0; i < graceList.length && !created; i++) {
                var wasPresent = false;
                for (var j = 0; j < existing.length; j++) {
                    if ((graceList[i].is && graceList[i].is(existing[j])) || graceList[i] === existing[j]) {
                        wasPresent = true;
                        break;
                    }
                }
                if (!wasPresent) created = graceList[i];
            }
            if (!created) {
                created = params.type.indexOf("after") >= 0 ? graceList[graceList.length - 1] : graceList[0];
            }
            if (!created.notes || created.notes.length !== 1)
                throw new Error("MuseScore created an unexpected grace chord");
            var note = created.notes[0];
            note.pitch = params.pitch;
            if (params.tpc !== undefined) note.tpc = params.tpc;
            if (note.pitch !== params.pitch)
                throw new Error("MuseScore did not retain grace-note pitch " + params.pitch);
            if (params.tpc !== undefined && note.tpc !== params.tpc)
                throw new Error("MuseScore did not retain grace-note TPC " + params.tpc);
            if (note.noteType !== expectedTypes[params.type])
                throw new Error("MuseScore created a different grace-note type");
            selectionState = {startStaff: params.staff, endStaff: params.staff + 1,
                              startTick: params.startTick, elements: [processElement(verify.element)],
                              totalDuration: verify.element.actualDuration ? verify.element.actualDuration.ticks : 0};
            return {success: true, changed: true, staff: params.staff, voice: voice,
                    startTick: params.startTick, type: params.type,
                    placement: params.type.indexOf("after") >= 0 ? "after" : "before",
                    note: {pitch: note.pitch, tpc: note.tpc, noteType: note.noteType},
                    graceNoteCount: graceList.length, currentSelection: selectionState};
        });
    }
    function notationCursor(params) {
        if (!curScore) throw new Error("No score open");
        if (!params || !Number.isInteger(params.staff) || params.staff < 0 || params.staff >= curScore.nstaves)
            throw new Error("staff must be a valid zero-based staff index");
        if (!Number.isInteger(params.startTick) || params.startTick < 0)
            throw new Error("startTick must be a nonnegative integer");
        var voice = params.voice === undefined ? 0 : params.voice;
        if (!Number.isInteger(voice) || voice < 0 || voice > 3) throw new Error("voice must be 0 to 3");
        var cursor = createCursor({startStaff: params.staff, startTick: params.startTick});
        cursor.voice = voice;
        cursor.rewindToTick(params.startTick);
        if (cursor.tick !== params.startTick || !cursor.element) throw new Error("No chord/rest at requested position");
        return cursor;
    }
    function addGraceSlur(params) {
        return executeWithUndo(function() {
            var chord = notationCursor(params).element;
            if (chord.type !== Element.CHORD || !chord.graceNotes.length) throw new Error("Main chord has no grace notes");
            var index = params.graceIndex === undefined ? 0 : params.graceIndex;
            if (!Number.isInteger(index) || index < 0 || index >= chord.graceNotes.length) throw new Error("Invalid graceIndex");
            var before = curScore.spanners.length;
            curScore.selection.clear();
            curScore.selection.select(chord.graceNotes[index].notes[0]);
            curScore.selection.select(chord.notes[0],true);
            cmd("add-slur");
            if (curScore.spanners.length !== before+1) throw new Error("Grace slur was not created");
            return {success:true,graceIndex:index,startTick:params.startTick};
        });
    }
    function addGraceNotes(params) {
        if (!params || !Array.isArray(params.notes) || !params.notes.length) return {error:"notes must be a nonempty grace-note array"};
        var after = String(params.type).indexOf("after") >= 0;
        var results = [];
        for (var i=0;i<params.notes.length;i++) {
            var index = after ? i : params.notes.length-1-i;
            var note = params.notes[index];
            var result = addGraceNote({staff:params.staff,voice:params.voice,startTick:params.startTick,
                                      type:params.type,pitch:note.pitch,tpc:note.tpc});
            if (result.error) return {error:result.error, completed:results};
            results.push(result);
        }
        return {success:true,count:params.notes.length,order:"input musical order",completed:results};
    }
    function addTremolo(params) {
        var types = {r8:TremoloType.R8, r16:TremoloType.R16, r32:TremoloType.R32, r64:TremoloType.R64, buzz:TremoloType.BUZZ_ROLL};
        if (!params || !Object.prototype.hasOwnProperty.call(types, params.type) || types[params.type] === undefined) return {error:"Unsupported single-chord tremolo type"};
        return executeWithUndo(function() {
            var chord = notationCursor(params).element;
            if (chord.type !== Element.CHORD) throw new Error("Tremolo requires a chord");
            var mark = chord.tremoloSingleChord;
            if (!mark) { mark = newElement(Element.TREMOLO_SINGLECHORD); mark.tremoloType = types[params.type]; chord.add(mark); }
            else mark.tremoloType = types[params.type];
            var actual = chord.tremoloSingleChord;
            if (!actual || actual.tremoloType !== types[params.type]) throw new Error("Tremolo readback failed");
            return {success:true, type:params.type, tremoloType:actual.tremoloType};
        });
    }
    function addArpeggio(params) {
        var types = {normal:0, up:1, down:2, bracket:3, upStraight:4, downStraight:5};
        if (!params || !Object.prototype.hasOwnProperty.call(types, params.type)) return {error:"Unsupported arpeggio type"};
        var span = params.span === undefined ? 1 : params.span;
        if (!Number.isInteger(span) || span < 1 || span > 1) return {error:"Only a single-staff arpeggio span is verified"};
        return executeWithUndo(function() {
            var chord = notationCursor(params).element;
            if (chord.type !== Element.CHORD) throw new Error("Arpeggio requires a chord");
            if (params.staff + span > curScore.nstaves) throw new Error("Arpeggio span exceeds staves");
            var mark = chord.arpeggio;
            if (!mark) { mark = newElement(Element.ARPEGGIO); mark.arpeggioType = types[params.type]; mark.arpeggioSpan = span; chord.add(mark); }
            else { mark.arpeggioType = types[params.type]; mark.arpeggioSpan = span; }
            var actual = chord.arpeggio;
            if (!actual || actual.arpeggioType !== types[params.type] || actual.arpeggioSpan !== span) throw new Error("Arpeggio readback failed");
            return {success:true, type:params.type, span:actual.arpeggioSpan};
        });
    }
    function addFermata(params) {
        var types = {normal:"fermataAbove", short:"fermataShortAbove", long:"fermataLongAbove", veryShort:"fermataVeryShortAbove", veryLong:"fermataVeryLongAbove"};
        if (!params || !Object.prototype.hasOwnProperty.call(types, params.type)) return {error:"Unsupported fermata type"};
        var stretch = params.timeStretch === undefined ? 1.5 : params.timeStretch;
        if (typeof stretch !== "number" || !isFinite(stretch) || stretch <= 0 || stretch > 10) return {error:"timeStretch must be greater than 0 and at most 10"};
        return executeWithUndo(function() {
            var cursor = notationCursor(params);
            var mark = newElement(Element.FERMATA);
            var symbol = types[params.type];
            if (params.below === true) symbol = symbol.replace("Above", "Below");
            mark.symbol = SymId[symbol];
            mark.timeStretch = stretch;
            cursor.add(mark);
            if (mark.symbol !== SymId[symbol] || Math.abs(mark.timeStretch - stretch) > 0.00001) throw new Error("Fermata readback failed");
            return {success:true, symbolName:symbol, symbol:mark.symbol, timeStretch:mark.timeStretch};
        });
    }
    function addOrnament(params) {
        var symbols = {trill:"ornamentTrill", mordent:"ornamentMordent", turn:"ornamentTurn", invertedTurn:"ornamentTurnInverted", shortTrill:"ornamentShortTrill"};
        if (!params || !Object.prototype.hasOwnProperty.call(symbols, params.type)) return {error:"Unsupported ornament type"};
        return executeWithUndo(function() {
            var chord = notationCursor(params).element;
            if (chord.type !== Element.CHORD) throw new Error("Ornament requires a chord");
            var mark = newElement(Element.ORNAMENT);
            mark.symbol = SymId[symbols[params.type]];
            chord.add(mark);
            if (mark.symbol !== SymId[symbols[params.type]]) throw new Error("Ornament readback failed");
            return {success:true, symbolName:symbols[params.type], symbol:mark.symbol};
        });
    }
    function getDrumset(params) {
        if (!curScore || !params || !Number.isInteger(params.staff) || params.staff < 0 || params.staff >= curScore.nstaves) return {error:"Invalid staff"};
        var instrument = curScore.staves[params.staff].part.instrumentAtTick(params.startTick || 0);
        var drums = instrument ? instrument.drumset : null;
        if (!drums) return {error:"Staff has no percussion drumset"};
        var notes = [];
        for (var pitch = 0; pitch < 128; pitch++) {
            if (drums.isValid(pitch)) notes.push({pitch:pitch, name:drums.name(pitch), line:drums.line(pitch), head:drums.noteHead(pitch), voice:drums.voice(pitch)});
        }
        return {instrumentId:instrument.instrumentId, notes:notes};
    }
    function addPercussionNote(params) {
        var mapping = getDrumset(params);
        if (mapping.error) return mapping;
        if (!Array.isArray(params.pitches) || params.pitches.length === 0) return {error:"pitches must list drum MIDI pitches"};
        for (var i = 0; i < params.pitches.length; i++) {
            var valid = false;
            for (var j = 0; j < mapping.notes.length; j++) if (mapping.notes[j].pitch === params.pitches[i]) valid = true;
            if (!valid) return {error:"Pitch is not defined in this drumset: " + params.pitches[i]};
        }
        if (params.tpcs !== undefined) return {error:"Percussion uses drum mapping, not pitched TPC spelling"};
        var result = addChord(params);
        if (!result.error) result.percussion = mapping.instrumentId;
        return result;
    }
    function setNoteHead(params) {
        var heads = {normal:NoteHeadGroup.HEAD_NORMAL, cross:NoteHeadGroup.HEAD_CROSS,
                     diamond:NoteHeadGroup.HEAD_DIAMOND, triangle:NoteHeadGroup.HEAD_TRIANGLE_DOWN};
        if (!params || heads[params.type] === undefined) return {error:"Unsupported notehead type"};
        return executeWithUndo(function() {
            var chord = notationCursor(params).element;
            if (chord.type !== Element.CHORD) throw new Error("Notehead requires a chord");
            var note = null;
            for (var i=0;i<chord.notes.length;i++) if (chord.notes[i].pitch === params.pitch) note = chord.notes[i];
            if (!note) throw new Error("Requested pitch is not in the chord");
            var instrument = curScore.staves[params.staff].part.instrumentAtTick(params.startTick);
            if (instrument && instrument.drumset) {
                // Percussion layout derives heads from the instrument's drum map.
                var drums = instrument.cloneDrumset();
                drums.setNoteHead(params.pitch, heads[params.type]);
                curScore.replaceDrumset(curScore.staves[params.staff].part, fraction(0,1), drums);
            }
            note.headGroup = heads[params.type];
            if (note.headGroup !== heads[params.type]) throw new Error("Notehead readback failed");
            return {success:true,pitch:note.pitch,type:params.type};
        });
    }
    function setAccidental(params) {
        var types = {natural:Accidental.NATURAL, sharp:Accidental.SHARP, flat:Accidental.FLAT,
                     doubleSharp:Accidental.SHARP2, doubleFlat:Accidental.FLAT2};
        if (!params || types[params.type] === undefined) return {error:"Unsupported accidental type"};
        var brackets = {none:0, parentheses:1, square:2};
        var bracket = params.bracket || "none";
        if (brackets[bracket] === undefined) return {error:"Unsupported accidental bracket"};
        return executeWithUndo(function() {
            var chord = notationCursor(params).element;
            if (chord.type !== Element.CHORD) throw new Error("Accidental requires a chord");
            var note = null;
            for (var i=0;i<chord.notes.length;i++) if (chord.notes[i].pitch === params.pitch) note = chord.notes[i];
            if (!note) throw new Error("Requested pitch is not in the chord");
            var mark = note.accidental;
            if (!mark) {mark = newElement(Element.ACCIDENTAL); mark.accidentalType = types[params.type]; note.add(mark);}
            else mark.accidentalType = types[params.type];
            mark.role = AccidentalRole.USER;
            mark.accidentalBracket = brackets[bracket];
            if (!note.accidental || note.accidental.accidentalType !== types[params.type] || note.accidental.accidentalBracket !== brackets[bracket]) throw new Error("Accidental readback failed");
            return {success:true,pitch:note.pitch,type:params.type,bracket:bracket};
        });
    }
    function addLyrics(params) {
        if (!params.lyrics || !Array.isArray(params.lyrics) || params.lyrics.length === 0) {
            return { error: "Lyrics must be specified as an array of strings" };
        }
        
        return executeWithUndo(function() {
            syncStateToSelection();
            
            var cursor = createCursor({ 
                startTick: selectionState.startTick, 
                startStaff: selectionState.startStaff 
            });
            
            var lyricsArray = params.lyrics.slice();
            var verse = params.verse || 0;
            var addedCount = 0;
            var skippedCount = 0;
            
            while (cursor.element && lyricsArray.length > 0) {
                var element = cursor.element;
                
                if (element.type === Element.CHORD || element.name === "Chord") {
                    var lyr = newElement(Element.LYRICS);
                    lyr.text = lyricsArray.shift();
                    lyr.verse = verse;
                    
                    cursor.add(lyr);
                    addedCount++;
                } else if (element.type === Element.REST || element.name === "Rest") {
                    skippedCount++;
                }
                
                if (!cursor.next()) break;
            }
            
            var finalElement = processElement(cursor.element) || selectionState.elements[0];
            var finalTick = cursor.tick;
            var staffIdx = cursor.staffIdx;
            
            selectionState = {
                startStaff: staffIdx,
                endStaff: staffIdx + 1,
                startTick: finalTick,
                elements: [finalElement],
                totalDuration: finalElement.durationTicks || selectionState.totalDuration
            };
            
            curScore.selection.clear();
            curScore.selection.selectRange(finalTick, finalTick + (finalElement.durationTicks || 0), staffIdx, staffIdx + 1);
            
            var message = `Added ${addedCount} lyrics`;
            if (skippedCount > 0) message += `, skipped ${skippedCount} rests`;
            if (lyricsArray.length > 0) message += `, ${lyricsArray.length} lyrics remaining`;
            
            return { 
                success: true, 
                message: message,
                addedCount: addedCount,
                skippedCount: skippedCount,
                remainingLyrics: lyricsArray,
                currentSelection: selectionState
            };
        });
    }
    function addDynamic(params) {
        if (!params || typeof params.type !== "string") return { error: "Dynamic type must be a string" };
        var validation = validateParams(params, ["type"]);
        if (!validation.valid) return validation;
        var allowed = ["ppp", "pp", "p", "mp", "mf", "f", "ff", "fff", "sfz", "fp", "rfz"];
        if (allowed.indexOf(params.type) < 0) return { error: "Unsupported dynamic: " + params.type };
        return executeWithUndo(function() {
            syncStateToSelection();
            var cursor = createCursor({ startTick: selectionState.startTick, startStaff: selectionState.startStaff });
            var dynamic = newElement(Element.DYNAMIC);
            if (typeof DynamicType === "undefined" || DynamicType[params.type.toUpperCase()] === undefined) {
                throw new Error("Standard dynamic types require MuseScore 4.6 or later");
            }
            dynamic.dynamicType = DynamicType[params.type.toUpperCase()];
            var symbols = { p: "dynamicPiano", m: "dynamicMezzo", f: "dynamicForte",
                            s: "dynamicSforzando", r: "dynamicRinforzando", z: "dynamicZ" };
            var display = "";
            for (var j = 0; j < params.type.length; j++) {
                display += "<sym>" + symbols[params.type[j]] + "</sym>";
            }
            dynamic.text = display;
            cursor.add(dynamic);
            return { success: true, message: "Dynamic " + params.type + " added", currentSelection: selectionState };
        });
    }
    function validateNotationRange(minChords, singleVoice) {
        if (!curScore) return { error: "No score open" };
        var selection = curScore.selection;
        var start = selection.startSegment;
        var end = selection.endSegment;
        var endTick = end ? end.tick : 0;
        // MuseScore can clamp a final-score selection to its last chord segment.
        // Our explicit range retains the intended exclusive end (the barline).
        if (typeof selectionState !== "undefined" && selectionState.startTick === (start ? start.tick : -1) && selectionState.totalDuration > 0)
            endTick = Math.max(endTick, selectionState.startTick + selectionState.totalDuration);
        if (!start || start.tick >= endTick)
            return { error: "Select an explicit nonempty tick range before adding notation" };
        if (selection.endStaff !== selection.startStaff + 1)
            return { error: "Notation commands require a single-staff range" };
        var count = 0;
        var voices = {};
        for (var segment = start; segment && segment.tick < endTick; segment = segment.next) {
            for (var voice = 0; voice < 4; voice++) {
                var element = segment.elementAt(selection.startStaff * 4 + voice);
                if (element && element.type === Element.CHORD) {
                    count++;
                    voices[voice] = true;
                }
            }
        }
        if (count < minChords) return { error: "Selected range requires at least " + minChords + " note/chord positions" };
        if (singleVoice && Object.keys(voices).length !== 1)
            return { error: "Slur range must contain notes in exactly one voice" };
        return { valid: true };
    }
    function addArticulation(params) {
        if (!params || typeof params.type !== "string") return { error: "Articulation type must be a string" };
        var validation = validateParams(params, ["type"]);
        if (!validation.valid) return validation;
        var actions = { staccato: "add-staccato", marcato: "add-marcato", tenuto: "add-tenuto", accent: "add-sforzato" };
        if (!Object.prototype.hasOwnProperty.call(actions, params.type)) return { error: "Unsupported articulation: " + params.type };
        var range = validateNotationRange(1, false);
        if (!range.valid) return range;
        return executeWithUndo(function() {
            cmd(actions[params.type]);
            return { success: true, message: "Articulation " + params.type + " added", currentSelection: selectionState };
        });
    }
    function addSlur(params) {
        var range = validateNotationRange(2, true);
        if (!range.valid) return range;
        return executeWithUndo(function() {
            var mapped = selectionState.elements["staff" + selectionState.startStaff];
            if (!Array.isArray(mapped)) throw new Error("Select an explicit range with selectCustomRange before adding a slur");
            var chords = [];
            for (var i=0;i<mapped.length;i++) if (mapped[i].name === "Chord") chords.push(mapped[i]);
            if (chords.length < 2) throw new Error("Slur requires two mapped chord positions");
            var first = notationCursor({staff:selectionState.startStaff,voice:chords[0].voice,startTick:chords[0].startTick}).element;
            var last = notationCursor({staff:selectionState.startStaff,voice:chords[chords.length-1].voice,startTick:chords[chords.length-1].startTick}).element;
            curScore.selection.clear();
            curScore.selection.select(first.notes[0]);
            curScore.selection.select(last.notes[0], true);
            cmd("add-slur");
            return { success: true, message: "Slur added", startTick:chords[0].startTick,
                     endTick:chords[chords.length-1].startTick, currentSelection: selectionState };
        });
    }
    function addTechniqueText(params) {
        var validation = validateParams(params, ["text"]);
        if (!validation.valid) return validation;
        if (!String(params.text).trim()) return { error: "Technique text must not be empty" };
        return executeWithUndo(function() {
            syncStateToSelection();
            var cursor = createCursor({ startTick: selectionState.startTick, startStaff: selectionState.startStaff });
            var marking = newElement(Element.STAFF_TEXT);
            marking.text = params.text;
            cursor.add(marking);
            return { success: true, message: "Technique text added", currentSelection: selectionState };
        });
    }
    function appendMeasure(params) {
        return executeWithUndo(function() {
            var count = params && params.count || 1;
            
            for (var i = 0; i < count; i++) {
                cmd("append-measure");
            }
            
            return { 
                success: true, 
                message: count + " measure(s) appended",
                currentSelection: selectionState
            };
        });
    }
    function insertMeasure(params) {
        return executeWithUndo(function() {
            cmd("insert-measure");
            syncStateToSelection();
            
            return { 
                success: true, 
                message: "Measure inserted",
                currentSelection: selectionState
            };
        });
    }
    function deleteSelection(params) {
        return executeWithUndo(function() {
            if (params && params.measure) {
                createCursor({ measure: params.measure });
            }
            
            cmd("delete");
            
            return { 
                success: true, 
                message: "Selection deleted",
                currentSelection: selectionState
            };
        });
    }
    function addInstrument(params) {
        var validation = validateParams(params, ["instrumentId"]);
        if (!validation.valid) return validation;
        
        return executeWithUndo(function() {
            curScore.appendPart(params.instrumentId);
            return { success: true, message: "Instrument " + params.instrumentId + " added" };
        });
    }
    function setStaffMute(params) {
        return { error: "setStaffMute is not implemented; use setStaffVisible for engraving visibility" };
        /*
        var validation = validateParams(params, ["staff"]);
        if (!validation.valid) return validation;
        
        return executeWithUndo(function() {
            var staff = curScore.staves && curScore.staves[params.staff] || 
                       (typeof curScore.staff === "function" ? curScore.staff(params.staff) : null);
            
            if (staff) {
                staff.invisible = Boolean(params.mute);
                return { success: true, message: "Staff " + (params.mute ? "muted" : "unmuted") };
            } else {
                return { error: "Staff not found" };
            }
        });
        */
    }
    function setStaffVisible(params) {
        var validation = validateParams(params, ["staff", "visible"]);
        if (!validation.valid) return validation;
        return executeWithUndo(function() {
            var staff = curScore.staves && curScore.staves[params.staff] ||
                       (typeof curScore.staff === "function" ? curScore.staff(params.staff) : null);
            if (!staff) return { error: "Staff not found" };
            staff.invisible = !Boolean(params.visible);
            return { success: true, message: "Staff visibility updated" };
        });
    }
    function getMidiChannels(params) {
        if (!curScore) return { error: "No score open" };
        var tick = params && params.tick !== undefined ? params.tick : 0;
        if (!Number.isInteger(tick) || tick < 0) return { error: "tick must be a nonnegative integer" };
        var parts = [];
        for (var i = 0; i < curScore.parts.length; i++) {
            var instrument = curScore.parts[i].instrumentAtTick(tick);
            var channels = [];
            if (instrument) {
                for (var j = 0; j < instrument.channels.length; j++) {
                    var channel = instrument.channels[j];
                    channels.push({channel: j, name: channel.name,
                                   program: channel.midiProgram, bank: channel.midiBank});
                }
            }
            parts.push({part: i, instrumentId: instrument ? instrument.instrumentId : null,
                        name: instrument ? instrument.longName : null, channels: channels});
        }
        return { tick: tick, parts: parts, scope: "Notation MIDI channels; audio resource selection is separate" };
    }
    function setMidiPatch(params) {
        return { error: "setMidiPatch does not control MuseScore 4 audio resources; use setPartInstrument" };
    }
    function setPartInstrument(params) {
        if (!curScore) return { error: "No score open" };
        if (!params || !Number.isInteger(params.part) || params.part < 0 || params.part >= curScore.parts.length)
            return { error: "part must be a valid zero-based part index" };
        if (typeof params.instrumentId !== "string" || !params.instrumentId.trim())
            return { error: "instrumentId must be a nonempty MuseScore instrument ID" };
        var partIndex = params.part;
        var instrumentId = params.instrumentId.trim();
        var current = curScore.parts[partIndex].instrumentAtTick(0);
        var previousId = current ? current.instrumentId : null;
        var requestedName = params.name === undefined ? (curScore.parts[partIndex].longName || "") : params.name;
        if (typeof requestedName !== "string") return {error:"name must be a string"};
        if (previousId === instrumentId && (!requestedName || curScore.parts[partIndex].longName === requestedName))
            return { success: true, changed: false, part: partIndex, instrumentId: instrumentId };
        return executeWithUndo(function() {
            if (previousId !== instrumentId) curScore.replaceInstrument(curScore.parts[partIndex], instrumentId);
            if (requestedName) curScore.setInstrumentName(curScore.parts[partIndex], fraction(0,1), requestedName);
            var updated = curScore.parts[partIndex].instrumentAtTick(0);
            var actualId = updated ? updated.instrumentId : null;
            if (requestedName && curScore.parts[partIndex].longName !== requestedName) throw new Error("Instrument name readback failed");
            if (actualId !== instrumentId)
                throw new Error("Instrument replacement failed; unknown instrumentId: " + instrumentId);
            return { success: true, changed: true, part: partIndex,
                     previousInstrumentId: previousId, instrumentId: actualId,
                     scope: "MuseScore instrument template, notation defaults, and playback sound" };
        });
    }
    function setInstrumentSound(params) {
        return { error: "setInstrumentSound is not implemented for MuseScore 4.7.4" };
        /*
        var validation = validateParams(params, ["staff", "instrumentId"]);
        if (!validation.valid) return validation;
        
        return executeWithUndo(function() {
            cmd("instruments");
            return { success: true, message: "Instrument dialog opened, manual selection required" };
        });
        */
    }
    function getPageLayout() {
        if (!curScore) return { error: "No score open" };
        var style = curScore.style;
        return { widthMm: style.value("pageWidth") * 25.4,
                 heightMm: style.value("pageHeight") * 25.4,
                 printableWidthMm: style.value("pagePrintableWidth") * 25.4,
                 leftMm: style.value("pageOddLeftMargin") * 25.4,
                 rightMm: (style.value("pageWidth") - style.value("pagePrintableWidth") - style.value("pageOddLeftMargin")) * 25.4,
                 topMm: style.value("pageOddTopMargin") * 25.4,
                 bottomMm: style.value("pageOddBottomMargin") * 25.4,
                 evenLeftMm: style.value("pageEvenLeftMargin") * 25.4,
                 evenTopMm: style.value("pageEvenTopMargin") * 25.4,
                 evenBottomMm: style.value("pageEvenBottomMargin") * 25.4,
                 pageCount: curScore.npages };
    }
    function setPageLayout(params) {
        if (!curScore) return { error: "No score open" };
        var names = ["widthMm", "heightMm", "leftMm", "rightMm", "topMm", "bottomMm"];
        for (var i = 0; i < names.length; i++) {
            var value = params && params[names[i]];
            if (typeof value !== "number" || !isFinite(value) || value < 0)
                return { error: names[i] + " must be a finite nonnegative number in millimeters" };
        }
        if (params.widthMm <= params.leftMm + params.rightMm || params.heightMm <= params.topMm + params.bottomMm)
            return { error: "Page margins must leave a positive printable area" };
        return executeWithUndo(function() {
            var values = {pageWidth: params.widthMm, pageHeight: params.heightMm,
                pagePrintableWidth: params.widthMm - params.leftMm - params.rightMm,
                pageOddLeftMargin: params.leftMm, pageEvenLeftMargin: params.leftMm,
                pageOddTopMargin: params.topMm, pageEvenTopMargin: params.topMm,
                pageOddBottomMargin: params.bottomMm, pageEvenBottomMargin: params.bottomMm};
            for (var name in values) {
                curScore.style.setValue(name, values[name] / 25.4);
                if (Math.abs(curScore.style.value(name) * 25.4 - values[name]) > 0.001)
                    throw new Error("Page setting was not applied: " + name);
            }
            return { success: true, layout: getPageLayout() };
        });
    }
    function setLayoutBreak(params) {
        if (!curScore) return { error: "No score open" };
        if (!params || !Number.isInteger(params.measure) || params.measure < 1)
            return { error: "measure must be a positive one-based measure number" };
        if (["line", "page", "none"].indexOf(params.type) < 0)
            return { error: "Layout break type must be line, page, or none" };
        var cursor = createCursor({startTick: 0, startStaff: 0, voice: 0});
        for (var i = 1; i < params.measure; i++) {
            if (!cursor.nextMeasure()) return { error: "Measure is outside the score" };
        }
        var measure = cursor.measure;
        if (!measure) return { error: "No target measure" };
        var breaks = [];
        for (var j = 0; j < measure.elements.length; j++) {
            var item = measure.elements[j];
            if (item.type === Element.LAYOUT_BREAK) {
                if (item.layoutBreakType === LayoutBreak.SECTION)
                    return { error: "A section break exists here; preserve its musical settings" };
                breaks.push(item);
            }
        }
        var target = params.type === "line" ? LayoutBreak.LINE : LayoutBreak.PAGE;
        if ((params.type === "none" && !breaks.length) ||
            (params.type !== "none" && breaks.length === 1 && breaks[0].layoutBreakType === target))
            return { success: true, changed: false, measure: params.measure, type: params.type };
        return executeWithUndo(function() {
            for (var k = 0; k < breaks.length; k++) measure.remove(breaks[k]);
            if (params.type !== "none") {
                var br = newElement(Element.LAYOUT_BREAK);
                br.layoutBreakType = target;
                measure.add(br);
            }
            return { success: true, changed: true, measure: params.measure, type: params.type };
        });
    }
    function writtenToConcertKey(fifths, interval) {
        // A chromatic semitone contributes seven fifths; a diatonic step twelve.
        var key = fifths + 7 * interval.chromatic - 12 * interval.diatonic;
        while (key < -7) key += 12;
        while (key > 7) key -= 12;
        return key;
    }
    function setKeySignature(params) {
        if (!curScore) return { error: "No score open" };
        if (!params || !Number.isInteger(params.fifths) || params.fifths < -7 || params.fifths > 7)
            return { error: "fifths must be an integer from -7 (flats) to 7 (sharps)" };
        if (!Number.isInteger(params.staff) || params.staff < 0 || params.staff >= curScore.nstaves)
            return { error: "staff must be a valid zero-based staff index" };
        if (!Number.isInteger(params.measure) || params.measure < 1)
            return { error: "measure must be a positive one-based measure number" };
        if (curScore.style.value("concertPitch"))
            return { error: "Written-key editing requires the score's concert pitch display to be off" };
        var cursor = createCursor({startTick: 0, startStaff: params.staff, voice: 0});
        for (var m = 1; m < params.measure; m++) {
            if (!cursor.nextMeasure()) return { error: "Measure is outside the score" };
        }
        if (!cursor.measure || !cursor.segment) return { error: "No music at target measure" };
        var staff = curScore.staves[params.staff];
        var interval = staff.transpose(cursor.fraction);
        var concert = writtenToConcertKey(params.fifths, interval);
        var tick = cursor.tick;
        var existing = null;
        for (var segment = cursor.measure.firstSegment; segment && segment.tick <= tick; segment = segment.next) {
            var item = segment.elementAt(params.staff * 4);
            if (item && item.type === Element.KEYSIG && segment.tick === tick) {
                existing = item;
                break;
            }
        }
        if (existing && existing.actualKey === params.fifths && existing.concertKey === concert)
            return { success: true, changed: false, staff: params.staff, measure: params.measure,
                     tick: tick, writtenFifths: params.fifths, concertFifths: concert };
        return executeWithUndo(function() {
            if (existing) removeElement(existing);
            var key = newElement(Element.KEYSIG);
            key.concertKey = concert;
            key.actualKey = params.fifths;
            cursor.add(key);
            return { success: true, changed: true, staff: params.staff, measure: params.measure,
                     tick: tick, writtenFifths: key.actualKey, concertFifths: key.concertKey };
        });
    }
    function setTimeSignature(params) {
        var validation = validateParams(params, ["numerator", "denominator"]);
        if (!validation.valid) return validation;
        
        return executeWithUndo(function() {
            var cursor = createCursor();
            var currTick = cursor.tick;
            var currStaff = cursor.staffIdx;

            var ts = newElement(Element.TIMESIG);
            ts.timesig = fraction(params.numerator, params.denominator);
            cursor.add(ts);

            return { 
                success: true, 
                message: "Time signature set to " + params.numerator + "/" + params.denominator
            };
        });
    }
    function setTempo(params) {
        if (!params || typeof params.bpm !== "number" || !isFinite(params.bpm) || params.bpm <= 0 || params.bpm > 1000)
            return {error:"bpm must be greater than 0 and at most 1000"};
        var units = {quarter:{factor:1,symbol:"metNoteQuarterUp"}, dottedQuarter:{factor:1.5,symbol:"metNoteQuarterUp"},
                     half:{factor:2,symbol:"metNoteHalfUp"}, eighth:{factor:0.5,symbol:"metNote8thUp"}};
        var unit = params.beatUnit || "quarter";
        if (!units[unit]) return {error:"Unsupported tempo beatUnit"};
        return executeWithUndo(function() {
            var cursor = params.staff !== undefined && params.startTick !== undefined ? notationCursor(params) : createCursor();
            var tempo = newElement(Element.TEMPO_TEXT);
            tempo.tempo = params.bpm * units[unit].factor / 60;
            tempo.text = (params.text ? String(params.text) + " " : "") + "<sym>" + units[unit].symbol + "</sym>" +
                         (unit === "dottedQuarter" ? "<sym>metAugmentationDot</sym>" : "") + " = " + params.bpm;
            cursor.add(tempo);
            if (Math.abs(tempo.tempo - params.bpm * units[unit].factor / 60) > 0.000001) throw new Error("Tempo readback failed");
            return {success:true, bpm:params.bpm, beatUnit:unit, quarterBpm:tempo.tempo*60, text:tempo.text};
        });
    }
    function getScore(params) {
        if (!curScore) return { error: "No score open" };
        
        try {
            return { success: true, analysis: getScoreSummary() };
        } catch (e) {
            return { error: e.toString() };
        }
    }
    function getScoreSummary() {
        if (!curScore) return { error: "No score open" };

        return executeWithUndo(function() {
            var tempState = selectionState;
            var score = {
                title: curScore.metaTag("workTitle") || curScore.title || "",
                numMeasures: curScore.nmeasures,
                measures: [],
                staves: []
            };
            
            // Analyze staves
            for (var i = 0; i < curScore.nstaves; i++) {
                var staff = curScore.staves && curScore.staves[i] || 
                           (typeof curScore.staff === "function" ? curScore.staff(i) : null);
                
                score.staves.push({
                    name: `staff${i}`,
                    shortName: staff ? staff.shortName : "",
                    visible: staff ? !staff.invisible : true
                });
            }

            // Analyze measures
            var cursor = createCursor({startTick: 0});
            var measureBoundaries = [];

            // Get measure boundaries
            for (var i = 0; i < curScore.nmeasures; i++) {
                var measure = {
                    measure: i + 1, 
                    startTick: cursor.tick,
                    numElements: 0, 
                    elements: {}
                };

                for (var j = 0; j < curScore.nstaves; j++) {
                    measure.elements[`staff${j}`] = [];
                }

                measureBoundaries.push(cursor.tick);
                score.measures.push(measure);
                cursor.nextMeasure();
            }

            // Process elements for each staff
            for (var k = 0; k < curScore.nstaves; k++) {
                cursor.rewind(0);
                var currentSegment = cursor.segment;

                while (currentSegment) {
                    var measureIdx = measureBoundaries.filter(function(tick) {
                        return tick <= currentSegment.tick;
                    }).length - 1;

                    for (var v = 0; v < 4; v++) {
                        var track = k * 4 + v;
                        var el = currentSegment.elementAt(track);
                        if (el) {
                            score.measures[measureIdx].numElements++;
                            var processedElement = processElement(el);
                            if (processedElement) {
                                processedElement.startTick = currentSegment.tick;
                                processedElement.voice = v;
                                score.measures[measureIdx].elements[`staff${k}`].push(processedElement);
                            }
                        }
                    }
                    currentSegment = currentSegment.next;
                }
            }

            // Restore state
            selectionState = tempState;
            return score;
        });
    }
