"""Keep both official MuseScore hosts on the same implementation."""
from pathlib import Path
import re
root = Path(__file__).resolve().parents[1]
qml = (root/'plugins/musescore-mcp-websocket.qml').read_text(encoding='utf-8')
version = re.search(r'version: "([^"]+)"', qml).group(1)
functions = '\n'.join(re.findall(r'    function \w+\(.*?\n    }', qml, re.S))
js = '// Generated by scripts/sync_musescore_commands.py; edit the QML source.\n'
js += 'var version="' + version + '", selectionState={startStaff:0,endStaff:1,startTick:0,elements:[]};\n' + functions + '\n'
(root/'src/scorebridge/musescore/commands.js').write_text(js, encoding='utf-8')
